### ISSUE TITLE
这是为什么

### ISSUE THREAD

**Issue by 2024ZC** [saermart/DouyinLiveWebFetcher#72]
C:\Users\A1532\PycharmProjects\pythonProject2\.venv\Scripts\python.exe C:\Users\A1532\PycharmProjects\pythonProject2\main.py 
Traceback (most recent call last):
  File "C:\Users\A1532\PycharmProjects\pythonProject2\main.py", line 13, in <module>
    DouyinLiveWebFetcher(live_id).start()
  File "C:\Users\A1532\PycharmProjects\pythonProject2\liveMan.py", line 94, in start
    self._connectWebSocket()
  File "C:\Users\A1532\PycharmProjects\pythonProject2\liveMan.py", line 166, in _connectWebSocket
    signature = generateSignature(wss)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A1532\PycharmProjects\pythonProject2\liveMan.py", line 60, in generateSignature
    ret = context.call('getSign', {'X-MS-STUB': md5_param})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A1532\PycharmProjects\pythonProject2\.venv\Lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A1532\PycharmProjects\pythonProject2\.venv\Lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A1532\PycharmProjects\pythonProject2\.venv\Lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\A1532\PycharmProjects\pythonProject2\.venv\Lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A1532\PycharmProjects\pythonProject2\.venv\Lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A1532\PycharmProjects\pythonProject2\.venv\Lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 语法错误

进程已结束，退出代码为 1

**Comment by 2024ZC** [comment]
![image](https://github.com/user-attachments/assets/e54999fb-f581-4af0-9ddf-0a573fac4db1)
原来之前地址格式填错了，现在能运行了但是没反应不知道为什么

**Comment by 2024ZC** [comment]
现在可以了，原因是在执行 JavaScript 代码时找不到 ‘jsdom’ 模块，安装一下就可以了
